version: '3.8'

# Settings and configurations that are common for all containers
x-minio-common:
  &minio-common
  image: quay.io/minio/minio
  restart: always
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    - MINIO_ROOT_USER= minioadmin
    - MINIO_ROOT_PASSWORD= minioadmin
    - MINIO_DISTRIBUTED_MODE_ENABLED=yes
    - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
  healthcheck:
    test:
      [
        "CMD",
        "curl",
        "-f",
        "http://localhost:9000/minio/health/live"
      ]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common
    container_name: minio1
    volumes:
      - carapp_data1-1:/data1
      - carapp_data1-2:/data2

  minio2:
    <<: *minio-common
    container_name: minio2
    volumes:
      - carapp_data2-1:/data1
      - carapp_data2-2:/data2

  minio3:
    <<: *minio-common
    container_name: minio3
    volumes:
      - carapp_data3-1:/data1
      - carapp_data3-2:/data2

  minio4:
    <<: *minio-common
    container_name: minio4
    volumes:
      - carapp_data4-1:/data1
      - carapp_data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8087:80"
      - "443:443"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    restart: always

volumes:
  carapp_test:
  carapp_data1-1:
  carapp_data1-2:
  carapp_data2-1:
  carapp_data2-2:
  carapp_data3-1:
  carapp_data3-2:
  carapp_data4-1:
  carapp_data4-2:
networks:
  carapp:
    driver: bridge